### ISSUE TITLE
Unable to authenticate (invalid_request)

### ISSUE THREAD

**Issue by boianradu** [hazcod/go-intigriti#83]
Using the example from README.md gives me a panic error.
To solve that I had to change the code to

```
cfg := config.Config{}

cfg.TokenCache = &config.CachedToken{}
cfg.Credentials.ClientID = "clientId"
cfg.Credentials.ClientSecret = "clientSecret"
inti, err := intigriti.New(cfg)
if err != nil {
log.Fatal(err)
}
``` 
Still, when I get the authentication link, it gives me **_invalid_request_**. The credentials for v2 are still valid (tested in Swagger)

I tried playing around with the config and the library and couldn't find a workaround.

**Comment by hazcod** [comment]
Hi there @boianradu , the panic should be fixed in https://github.com/hazcod/go-intigriti/releases/tag/v1.4.2.
I'm currently looking into the `invalid_request` for you.

**Comment by hazcod** [comment]
Hey @boianradu , can you please try with v1.4.4? So changing the version in `go.mod` and doing a `go mod tidy`.
I've updated the SDK to work with the latest API revision.

**Comment by boianradu** [comment]
<img width="1016" alt="image" src="https://github.com/hazcod/go-intigriti/assets/9000242/6dc52e0d-1aff-4296-8711-e38aaa7af711">

**Comment by hazcod** [comment]
Are you sure the client_id is correct btw? I asked around and I saw some errors indicating unknown clientid.

**Comment by boianradu** [comment]
As discussed by email, yes, the client is legit, being the one used in Swagger V2 successfully

**Comment by hazcod** [comment]
Closing this since it was due to a wrong redirectUri on company configuration side.
